#pragma once

// Autogenerated from info.hpp.info

#include <string_view>
namespace btl::info {

using sv = std::string_view;

static constexpr auto PROJECT_NAME=sv("build-watch");
static constexpr auto PROJECT_VERSION=sv("1.0");
static constexpr auto PROJECT_VERSION_MAJOR=sv("1");
static constexpr auto PROJECT_VERSION_MINOR=sv("0");
static constexpr auto PROJECT_VERSION_PATCH=sv("");

}
